services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86
    volumes:
      - immich_uploads:/data
      - /etc/localtime:/etc/localtime:ro
      - immich_synology_import:/import
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE_NAME: immich
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86
    volumes:
      - model-cache:/cache
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    deploy:
      placement:
        constraints:
          - node.labels.arch == x86
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: 'HDD'
    volumes:
      - immich_database:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always

volumes:
  model-cache:
  immich_database:
    driver: local
    driver_opts:
      type: nfs
      o: addr=files.shearer.live,nolock,rw
      device: ":/volume1/docker/immich/database"
  immich_uploads:
    driver: local
    driver_opts:
      type: nfs
      o: addr=files.shearer.live,nolock,rw
      device: ":/volume1/docker/immich/uploads"
  immich_synology_import:
    driver: local
    driver_opts:
      type: nfs
      o: addr=files.shearer.live,nolock,rw
      device: ":/volume1/docker/immich/uploads/jason_synology_import"
