version: '3.6'
services:
  telegraf:
    image: telegraf:latest
    hostname: "{{.Node.ID}}"
    entrypoint: /bin/sh -c "chmod 666 /var/run/docker.sock && /entrypoint.sh telegraf"
    restart: unless-stopped
    volumes:
    - telegraf:/etc/telegraf
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influx
    ports:
    - '8125:8125'
    deploy:
      mode: global

  influx:
    image: influxdb:latest
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
    ports:
      - '8086:8086'
    volumes:
      - influx:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    depends_on:
      - influx
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_INSTALL_PLUGINS=
    ports:
      - '3000:3000'
    volumes:
      - grafana:/var/lib/grafana

volumes:
  telegraf:
    driver: local
    driver_opts:
      type: nfs
      o: addr=files.shearer.live,nolock,rw
      device: ":/volume1/docker/telegraf"
  influx:
    driver: local
    driver_opts:
      type: nfs
      o: addr=files.shearer.live,nolock,rw
      device: ":/volume1/docker/influx"
  grafana:
    driver: local
    driver_opts:
      type: nfs
      o: addr=files.shearer.live,nolock,rw
      device: ":/volume1/docker/grafana"
